### ISSUE TITLE
License for the project

### ISSUE THREAD

**Issue by yury-s** [greenjava/win-ldd#1]
We'd like to use `win-ldd` in our project but there is currently no license. Can you add a license to the code (e.g. a BSD license header would be sufficient I believe)?

**Comment by greenjava** [comment]
Fixed in d31002c (short and simple permissive MIT license)
You can use this project freely, but be careful, it's an old code, good luck :sweat_smile:

**Comment by yury-s** [comment]
Thanks for such a quick turnaround and for creating this project too!
